from __future__ import annotations

import re


NORMALIZED_FIELDS = [
    "source_record_id",
    "timestamp_opened",
    "timestamp_closed",
    "machine_id",
    "machine_name",
    "zone",
    "issue",
    "failure_code",
    "severity",
    "operator_note",
    "resolution_note",
    "downtime_minutes",
    "labor_hours",
    "technician",
    "status",
    "source",
    "matched_machine",
]

BACKEND_CREATED_FIELDS = {"source", "matched_machine"}

REQUIRED_OR_NEAR_REQUIRED_FIELDS = {
    "machine_id",
    "timestamp_opened",
    "issue",
    "severity",
    "downtime_minutes",
}

STRONGLY_PREFERRED_FIELDS = {
    "machine_name",
    "zone",
    "operator_note",
    "resolution_note",
    "technician",
    "status",
}

FIELD_PRIORITY = [
    "source_record_id",
    "machine_id",
    "machine_name",
    "timestamp_opened",
    "timestamp_closed",
    "zone",
    "issue",
    "failure_code",
    "severity",
    "operator_note",
    "resolution_note",
    "downtime_minutes",
    "labor_hours",
    "technician",
    "status",
]

FIELD_CUES: dict[str, list[str]] = {
    "source_record_id": [
        "Work Order ID",
        "Ticket No",
        "Work Order",
        "Work Order Number",
        "Work Order No",
        "Work Order #",
        "WO",
        "WO Number",
        "WO No",
        "WO #",
        "WO ID",
        "Ticket",
        "Ticket Number",
        "Ticket ID",
        "Ticket #",
        "Maintenance Ticket",
        "Maintenance Ticket No",
        "Maintenance Ticket ID",
        "Request ID",
        "Service Request",
        "Service Request ID",
        "Service Request No",
        "Case ID",
        "Case Number",
        "Job ID",
        "Job Number",
        "Task ID",
        "Record ID",
        "Reference ID",
        "Reference Number",
        "Repair Order",
        "Repair Order ID",
        "Repair Order Number",
        "Maintenance ID",
        "Maintenance Record ID",
        "id",
        "record",
        "ref",
        "ref no",
        "order no",
        "job no",
        "case no",
        "ticket no",
        "wo no",
        "request no",
    ],
    "timestamp_opened": [
        "Date Opened",
        "Opened",
        "Created On",
        "Opened At",
        "Opened Date",
        "Open Date",
        "Created",
        "Created Date",
        "Created At",
        "Date Created",
        "Reported Date",
        "Reported At",
        "Date Reported",
        "Issue Opened",
        "Issue Created",
        "Ticket Opened",
        "Ticket Created",
        "Work Order Opened",
        "Work Order Created",
        "Request Opened",
        "Request Created",
        "Start Date",
        "Start Time",
        "Started",
        "Started At",
        "Event Time",
        "Event Date",
        "Failure Time",
        "Failure Date",
        "Breakdown Time",
        "Breakdown Date",
        "Breakdown Start",
        "Downtime Start",
        "Problem Start",
        "Call Time",
        "Call Date",
        "Logged At",
        "Logged Date",
        "Entry Date",
        "Submitted At",
        "Submitted Date",
        "dt opened",
        "open dt",
        "created dt",
    ],
    "timestamp_closed": [
        "Date Closed",
        "Closed",
        "Closed At",
        "Closed Date",
        "Close Date",
        "Completed",
        "Completed At",
        "Completed Date",
        "Date Completed",
        "Resolved",
        "Resolved At",
        "Resolved Date",
        "Date Resolved",
        "Finished",
        "Finished At",
        "Finish Date",
        "End Date",
        "End Time",
        "Ended",
        "Ended At",
        "Repair Completed",
        "Repair Completed At",
        "Work Completed",
        "Work Complete Date",
        "Ticket Closed",
        "Ticket Completed",
        "Work Order Closed",
        "Work Order Completed",
        "Request Closed",
        "Request Completed",
        "Downtime End",
        "Breakdown End",
        "Problem End",
        "Restored At",
        "Restored Date",
        "Back Online",
        "Back Online Time",
        "Back In Service",
        "Returned To Service",
        "Return To Service Time",
        "closed dt",
        "complete dt",
    ],
    "machine_id": [
        "Asset ID",
        "Machine",
        "Equipment",
        "Machine ID",
        "Machine Code",
        "Machine Number",
        "Machine No",
        "Machine #",
        "Asset",
        "Asset Number",
        "Asset No",
        "Asset #",
        "Asset Code",
        "Asset Tag",
        "Equipment ID",
        "Equipment Code",
        "Equipment Number",
        "Equipment No",
        "Equipment #",
        "Equipment Tag",
        "Unit ID",
        "Unit Number",
        "Unit No",
        "Line ID",
        "Line Number",
        "Line Code",
        "Cell ID",
        "Cell Number",
        "Station ID",
        "Station Number",
        "Station Code",
        "Device ID",
        "Device Number",
        "Resource ID",
        "Resource Number",
        "Tool ID",
        "Tool Number",
        "Machine Tag",
        "Equipment Tag ID",
        "CMMS Asset ID",
        "ERP Asset ID",
        "Plant Asset ID",
        "Internal Asset ID",
        "equip",
        "eqpt",
        "assetid",
        "machineid",
        "equipmentid",
        "equip id",
        "eq id",
        "mach id",
    ],
    "machine_name": [
        "Asset Name",
        "Line Name",
        "Equipment Description",
        "Machine Name",
        "Machine Description",
        "Machine Label",
        "Machine Title",
        "Asset Description",
        "Asset Label",
        "Equipment Name",
        "Equipment Desc",
        "Equipment Label",
        "Equipment Title",
        "Line Description",
        "Production Line",
        "Cell Name",
        "Cell Description",
        "Station Name",
        "Station Description",
        "Tool Name",
        "Tool Description",
        "Resource Name",
        "Resource Description",
        "Device Name",
        "Device Description",
        "Unit Name",
        "Unit Description",
        "Display Name",
        "machine desc",
        "asset desc",
        "equip desc",
        "equipment desc",
        "line desc",
        "machine name",
        "asset name",
        "equipment name",
        "equip name",
        "line name",
    ],
    "zone": [
        "Area",
        "Department",
        "Plant Zone",
        "Zone",
        "Plant Area",
        "Factory Area",
        "Factory Zone",
        "Production Area",
        "Production Zone",
        "Work Area",
        "Work Center",
        "Work Centre",
        "Department",
        "Dept",
        "Line Area",
        "Process Area",
        "Process Zone",
        "Manufacturing Area",
        "Manufacturing Zone",
        "Location",
        "Asset Location",
        "Equipment Location",
        "Machine Location",
        "Cell Location",
        "Site Area",
        "Plant Location",
        "Facility Area",
        "Facility Zone",
        "Shop",
        "Shop Area",
        "Bay",
        "Room",
        "Building Area",
        "Cost Center",
        "Cost Centre",
        "loc",
        "workcenter",
    ],
    "issue": [
        "Problem",
        "Failure Desc",
        "Issue",
        "Failure Description",
        "Failure",
        "Issue Description",
        "Problem Description",
        "Fault",
        "Fault Description",
        "Defect",
        "Defect Description",
        "Symptom",
        "Symptom Description",
        "Condition",
        "Condition Description",
        "Maintenance Issue",
        "Reported Issue",
        "Reported Problem",
        "Observed Problem",
        "Observed Issue",
        "Trouble",
        "Trouble Description",
        "Breakdown Reason",
        "Breakdown Description",
        "Failure Reason",
        "Fault Reason",
        "Problem Type",
        "Issue Type",
        "Failure Type",
        "Repair Reason",
        "Service Reason",
        "Complaint",
        "Operator Complaint",
        "Machine Problem",
        "Equipment Problem",
        "Root Problem",
        "Primary Issue",
        "Main Issue",
        "failure desc",
        "issue desc",
        "problem desc",
        "fault desc",
        "fail desc",
    ],
    "failure_code": [
        "Failure Code",
        "Cause Code",
        "Fault Code",
        "Error Code",
        "Alarm Code",
        "Reason Code",
        "Issue Code",
        "Problem Code",
        "Defect Code",
        "Failure Type Code",
        "Failure Class",
        "Failure Category",
        "Cause",
        "Cause ID",
        "Root Cause Code",
        "Root Cause",
        "RC Code",
        "RC",
        "Failure Mode",
        "Failure Mode Code",
        "FM Code",
        "Fault ID",
        "Alarm ID",
        "Diagnostic Code",
        "Trouble Code",
        "Condition Code",
        "Repair Code",
        "Maintenance Code",
        "Symptom Code",
        "Event Code",
        "Stop Code",
        "Downtime Code",
        "Breakdown Code",
        "code",
        "alarm",
        "root cause",
    ],
    "severity": [
        "Priority",
        "Criticality",
        "Severity",
        "Risk",
        "Risk Level",
        "Impact",
        "Impact Level",
        "Urgency",
        "Urgency Level",
        "Importance",
        "Priority Level",
        "Severity Level",
        "Criticality Level",
        "Failure Severity",
        "Issue Severity",
        "Problem Severity",
        "Alarm Severity",
        "Fault Severity",
        "Event Severity",
        "Maintenance Priority",
        "Work Priority",
        "Job Priority",
        "Ticket Priority",
        "Request Priority",
        "Service Priority",
        "Downtime Priority",
        "Production Impact",
        "Business Impact",
        "Critical Flag",
        "Critical",
        "prio",
        "sev",
        "crit",
    ],
    "operator_note": [
        "Tech Notes",
        "Operator Comment",
        "Notes",
        "Technician Notes",
        "Tech Note",
        "Operator Notes",
        "Operator Note",
        "Operator Comments",
        "Maintenance Notes",
        "Maintenance Comment",
        "Problem Notes",
        "Issue Notes",
        "Failure Notes",
        "Fault Notes",
        "Observation",
        "Observed Condition",
        "Observed Notes",
        "Reported Notes",
        "Reported Condition",
        "User Notes",
        "User Comment",
        "Comment",
        "Comments",
        "Description Notes",
        "Symptom Notes",
        "Symptom Description",
        "Initial Notes",
        "Initial Observation",
        "Complaint Notes",
        "Operator Complaint",
        "Technician Comment",
        "Inspection Notes",
        "Finding",
        "Findings",
        "Diagnosis Notes",
        "Diagnostic Notes",
        "Narrative",
        "Event Notes",
        "Event Description",
        "Details",
        "Additional Details",
        "Work Notes",
    ],
    "resolution_note": [
        "Action Taken",
        "Repair Notes",
        "Corrective Action",
        "Repair Action",
        "Repair Description",
        "Repair Performed",
        "Fix",
        "Fix Description",
        "Fix Performed",
        "Corrective Action Taken",
        "Corrective Notes",
        "Correction",
        "Correction Notes",
        "Action",
        "Actions",
        "Action Notes",
        "Maintenance Action",
        "Maintenance Performed",
        "Work Performed",
        "Work Completed",
        "Resolution",
        "Resolution Notes",
        "Resolution Description",
        "Remedy",
        "Remedy Notes",
        "Repair Summary",
        "Service Performed",
        "Service Notes",
        "Technician Action",
        "Technician Resolution",
        "Completed Work",
        "Actual Work",
        "Repair Details",
        "Follow Up Action",
        "Repair Comment",
        "Closeout Notes",
        "Closure Notes",
        "Closing Notes",
        "Root Cause Action",
        "Preventive Action",
        "Countermeasure",
    ],
    "downtime_minutes": [
        "Downtime Minutes",
        "Time Lost",
        "Stopped Minutes",
        "Downtime",
        "Downtime Min",
        "Downtime Mins",
        "Down Time",
        "Down Time Minutes",
        "Machine Downtime",
        "Machine Downtime Minutes",
        "Line Downtime",
        "Line Downtime Minutes",
        "Stopped Time",
        "Stop Time",
        "Stop Minutes",
        "Stoppage Minutes",
        "Stoppage Time",
        "Time Stopped",
        "Time Down",
        "Minutes Down",
        "Minutes Stopped",
        "Lost Time",
        "Production Lost Time",
        "Lost Production Time",
        "Unavailable Minutes",
        "Outage Minutes",
        "Outage Time",
        "Breakdown Minutes",
        "Breakdown Duration",
        "Downtime Duration",
        "Repair Downtime",
        "Runtime Lost",
        "Loss Time",
        "Delay Minutes",
        "Delay Time",
        "down mins",
        "down min",
        "stopped mins",
        "stopped min",
        "mins down",
    ],
    "labor_hours": [
        "Labor Hours",
        "Labor",
        "Labour",
        "Labor Time",
        "Labour Time",
        "Labor Hrs",
        "Labour Hrs",
        "Labour Hours",
        "Work Hours",
        "Work Hrs",
        "Technician Hours",
        "Tech Hours",
        "Maintenance Hours",
        "Repair Hours",
        "Service Hours",
        "Man Hours",
        "Manhours",
        "Man-Hours",
        "Person Hours",
        "Person-Hours",
        "Wrench Time",
        "Time Worked",
        "Effort Hours",
        "Actual Hours",
        "Actual Labor",
        "Actual Labour",
        "Reported Hours",
        "Booked Hours",
        "Logged Hours",
        "hrs",
        "work hrs",
        "tech hrs",
        "repair hrs",
        "service hrs",
    ],
    "technician": [
        "Technician",
        "Assigned Tech",
        "Maintenance Owner",
        "Tech",
        "Technician Name",
        "Assigned Technician",
        "Assigned To",
        "Owner",
        "Work Owner",
        "Maintenance Technician",
        "Maintenance Tech",
        "Repair Technician",
        "Repair Tech",
        "Service Technician",
        "Service Tech",
        "Mechanic",
        "Assigned Mechanic",
        "Maintainer",
        "Engineer",
        "Maintenance Engineer",
        "Responsible Person",
        "Responsible Technician",
        "Completed By",
        "Closed By",
        "Resolved By",
        "Performed By",
        "Repaired By",
        "Fixed By",
        "Worker",
        "Employee",
        "Employee Name",
        "Employee ID",
        "Craftsperson",
        "Crew Member",
        "Task Owner",
        "Job Owner",
    ],
    "status": [
        "Status",
        "Completion Status",
        "Work Order Status",
        "Ticket Status",
        "Request Status",
        "Job Status",
        "Task Status",
        "Maintenance Status",
        "Completion",
        "Completion State",
        "Complete Status",
        "Closed Status",
        "State",
        "Current State",
        "Current Status",
        "Progress",
        "Progress Status",
        "Workflow Status",
        "Resolution Status",
        "Close Status",
        "Repair Status",
        "Open Closed",
        "Open/Closed",
    ],
}

KEYWORD_RULES: dict[str, dict[str, int]] = {
    "source_record_id": {
        "work": 2,
        "order": 3,
        "ticket": 4,
        "request": 3,
        "record": 3,
        "reference": 3,
        "ref": 2,
        "case": 2,
        "job": 2,
        "id": 2,
        "number": 1,
        "no": 1,
    },
    "timestamp_opened": {
        "opened": 5,
        "open": 4,
        "created": 4,
        "reported": 3,
        "started": 4,
        "start": 4,
        "event": 2,
        "failure": 2,
        "logged": 3,
        "submitted": 2,
        "date": 2,
        "time": 2,
    },
    "timestamp_closed": {
        "closed": 5,
        "close": 4,
        "completed": 4,
        "complete": 3,
        "resolved": 4,
        "finished": 3,
        "ended": 3,
        "end": 3,
        "restored": 4,
        "online": 3,
        "date": 2,
        "time": 2,
    },
    "machine_id": {
        "machine": 4,
        "asset": 4,
        "equipment": 4,
        "equip": 3,
        "unit": 3,
        "line": 2,
        "cell": 2,
        "station": 2,
        "device": 2,
        "resource": 2,
        "tool": 2,
        "tag": 2,
        "code": 1,
        "id": 3,
        "number": 2,
        "no": 1,
    },
    "machine_name": {
        "machine": 3,
        "asset": 3,
        "equipment": 3,
        "equip": 2,
        "line": 2,
        "cell": 2,
        "station": 2,
        "device": 2,
        "resource": 2,
        "unit": 2,
        "name": 4,
        "description": 3,
        "desc": 3,
        "label": 3,
        "title": 2,
    },
    "zone": {
        "area": 5,
        "zone": 5,
        "department": 4,
        "dept": 4,
        "plant": 3,
        "factory": 3,
        "production": 2,
        "work": 1,
        "center": 2,
        "centre": 2,
        "location": 4,
        "loc": 3,
        "shop": 2,
        "bay": 2,
        "room": 2,
        "facility": 2,
    },
    "issue": {
        "problem": 5,
        "issue": 5,
        "failure": 4,
        "fault": 4,
        "defect": 3,
        "symptom": 3,
        "trouble": 3,
        "breakdown": 3,
        "reason": 2,
        "complaint": 2,
        "desc": 2,
        "description": 2,
    },
    "failure_code": {
        "failure": 3,
        "cause": 4,
        "fault": 3,
        "error": 3,
        "alarm": 3,
        "reason": 2,
        "root": 3,
        "rc": 3,
        "mode": 2,
        "diagnostic": 3,
        "event": 2,
        "stop": 2,
        "breakdown": 2,
        "code": 5,
        "id": 2,
    },
    "severity": {
        "priority": 5,
        "severity": 5,
        "criticality": 5,
        "risk": 4,
        "impact": 3,
        "urgency": 3,
        "importance": 2,
        "critical": 3,
        "level": 2,
        "prio": 4,
        "sev": 4,
        "crit": 4,
    },
    "operator_note": {
        "note": 4,
        "notes": 4,
        "comment": 4,
        "comments": 4,
        "operator": 4,
        "tech": 2,
        "technician": 2,
        "observation": 3,
        "observed": 3,
        "reported": 2,
        "details": 3,
        "finding": 3,
        "findings": 3,
        "diagnosis": 2,
        "narrative": 3,
        "symptom": 2,
    },
    "resolution_note": {
        "action": 5,
        "repair": 5,
        "fix": 5,
        "fixed": 4,
        "resolution": 4,
        "corrective": 5,
        "correction": 3,
        "remedy": 3,
        "work": 2,
        "performed": 3,
        "service": 2,
        "closeout": 3,
        "closure": 3,
        "closing": 3,
        "completed": 2,
        "countermeasure": 3,
    },
    "downtime_minutes": {
        "downtime": 5,
        "down": 4,
        "stopped": 5,
        "stop": 4,
        "stoppage": 4,
        "lost": 4,
        "loss": 3,
        "minutes": 4,
        "minute": 4,
        "mins": 4,
        "min": 4,
        "time": 2,
        "outage": 3,
        "delay": 3,
        "duration": 3,
        "breakdown": 2,
    },
    "labor_hours": {
        "labor": 5,
        "labour": 5,
        "hours": 4,
        "hour": 4,
        "hrs": 4,
        "hr": 4,
        "technician": 2,
        "tech": 2,
        "maintenance": 2,
        "repair": 2,
        "service": 2,
        "man": 2,
        "person": 2,
        "wrench": 3,
        "effort": 3,
        "worked": 3,
    },
    "technician": {
        "technician": 5,
        "tech": 4,
        "assigned": 4,
        "owner": 4,
        "mechanic": 4,
        "maintainer": 4,
        "engineer": 3,
        "responsible": 3,
        "completed": 2,
        "closed": 2,
        "resolved": 2,
        "performed": 3,
        "repaired": 3,
        "fixed": 3,
        "worker": 3,
        "employee": 3,
        "crew": 3,
    },
    "status": {
        "status": 5,
        "state": 4,
        "completion": 4,
        "complete": 3,
        "closed": 3,
        "open": 3,
        "progress": 3,
        "workflow": 3,
        "done": 3,
        "finished": 3,
        "resolved": 3,
    },
}

IGNORED_COLUMN_CUES = {
    "shift",
    "reporter",
    "reported by",
    "part replaced",
    "pm related",
    "preventive maintenance related",
    "temperature",
    "temp",
    "vibration",
    "pressure",
    "runtime hours",
    "run hours",
    "operating hours",
    "error count",
    "fault count",
    "alarm count",
    "last maintenance",
    "next maintenance",
    "downtime cost per minute",
    "cost per minute",
    "map x",
    "map y",
    "x",
    "y",
    "manufacturer",
    "model",
    "installed date",
    "energy usage",
    "throughput",
}

EXACT_MATCH_CONFIDENCE = 1.0
FUZZY_MATCH_MIN_CONFIDENCE = 0.86
FUZZY_MATCH_MIN_MARGIN = 0.04
KEYWORD_MATCH_MIN_SCORE = 4
KEYWORD_MATCH_MIN_MARGIN = 2


def normalize_column_name(column_name: str) -> str:
    normalized = column_name.strip().lower()
    normalized = normalized.replace("&", " and ")
    normalized = re.sub(r"[/#_-]+", " ", normalized)
    normalized = re.sub(r"[^a-z0-9\s]", " ", normalized)
    normalized = re.sub(r"\s+", " ", normalized)
    return normalized.strip()


def tokenize_column_name(column_name: str) -> list[str]:
    normalized = normalize_column_name(column_name)
    return normalized.split() if normalized else []


def build_exact_cue_lookup() -> dict[str, str]:
    lookup: dict[str, str] = {}
    priority = {field: index for index, field in enumerate(FIELD_PRIORITY)}

    for field, cues in FIELD_CUES.items():
        for cue in cues:
            normalized_cue = normalize_column_name(cue)
            existing_field = lookup.get(normalized_cue)

            if existing_field is None or priority[field] < priority[existing_field]:
                lookup[normalized_cue] = field

    return lookup


EXACT_CUE_LOOKUP = build_exact_cue_lookup()
